SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Indexes */

DROP INDEX FORM_FIELD_NAME ON TBL_FORM_FIELD_META;
DROP INDEX FK_FORM_ID_INDEX ON TBL_FORM_FIELD_META;
DROP INDEX INDEX_FORM_FIELD_VALUE ON TBL_FORM_FIELD_VALUE;
DROP INDEX FORM_NAME_UNIQUE ON TBL_FORM_META;



/* Drop Tables */

DROP TABLE IF EXISTS TBL_ENROLLMENT;
DROP TABLE IF EXISTS TBL_FORM_FIELD_OPTION;
DROP TABLE IF EXISTS TBL_FORM_FIELD_META;
DROP TABLE IF EXISTS TBL_FORM_FIELD_VALUE;
DROP TABLE IF EXISTS TBL_FORM_META;
DROP TABLE IF EXISTS TBL_USER_INFO;




/* Create Tables */

CREATE TABLE TBL_ENROLLMENT
(
	-- 唯一的注册号
	REGISTER_ID varchar(48) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '唯一的注册号',
	-- 表单标示
	FORM_ID bigint NOT NULL COMMENT '表单标示',
	-- 电话号码
	PHONE_NUMBER varchar(45) COMMENT '电话号码',
	APPLICANT_NAME varchar(100),
	-- 身份证号
	ID varchar(18) COMMENT '身份证号',
	-- 注册状态
	STATUS varchar(10) NOT NULL COMMENT '注册状态',
	-- for search 
	SEARCH_FIELD varchar(2000) COMMENT 'for search ',
	-- 注册日期
	REGISTER_DATE datetime NOT NULL COMMENT '注册日期',
	-- 更新时间戳
	UPDATED_TIMESTAMP datetime NOT NULL COMMENT '更新时间戳',
	PRIMARY KEY (REGISTER_ID),
	UNIQUE (REGISTER_ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE TBL_FORM_FIELD_META
(
	FIELD_ID bigint(20) NOT NULL AUTO_INCREMENT,
	-- form 编号
	FORM_ID bigint(20) NOT NULL COMMENT 'form 编号',
	-- 是否是必填字段
	REQUIRED varchar(10) COMMENT '是否是必填字段',
	FIELD_NAME varchar(100) NOT NULL,
	FIELD_TYPE varchar(20) NOT NULL,
	FIELD_CONSTRAINT varchar(200),
	FIELD_POSITION int NOT NULL,
	FIELD_DEFAULT_VALUE varchar(300),
	FIELD_STYLE varchar(500),
	-- 字段的显示值
	FIELD_LABEL varchar(100) NOT NULL COMMENT '字段的显示值',
	-- email
	-- text
	-- tel
	-- password
	FIELD_SUBTYPE varchar(10) COMMENT 'email
text
tel
password',
	FIELD_IS_SLOT varchar(10),
	-- 是否作为唯一的申请标示
	IS_UNIQUE_KEY varchar(10) COMMENT '是否作为唯一的申请标示',
	PRIMARY KEY (FIELD_ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;


CREATE TABLE TBL_FORM_FIELD_OPTION
(
	-- 字段编号
	FIELD_ID bigint(20) NOT NULL COMMENT '字段编号',
	-- 字段在form的序号
	POSITION int NOT NULL COMMENT '字段在form的序号',
	-- 字段的值
	VALUE varchar(45) NOT NULL COMMENT '字段的值',
	-- 字段的显示值
	LABEL varchar(200) NOT NULL COMMENT '字段的显示值',
	SLOT varchar(20),
	-- 是否默认选中
	SELECTED varchar(10) COMMENT '是否默认选中',
	DESCRIPTION varchar(500),
	PRIMARY KEY (FIELD_ID, POSITION)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;


CREATE TABLE TBL_FORM_FIELD_VALUE
(
	-- 注册号
	REGISTER_ID varchar(48) NOT NULL COMMENT '注册号',
	-- 字段编号
	FIELD_ID bigint(20) NOT NULL COMMENT '字段编号',
	-- form 编号
	FORM_ID bigint(20) NOT NULL COMMENT 'form 编号',
	-- 输入框值
	FIELD_VALUE varchar(1500) COMMENT '输入框值',
	-- 如果是Select, Checkbox, Radio显示对应的值
	FIELD_DISPLAY varchar(100) COMMENT '如果是Select, Checkbox, Radio显示对应的值',
	-- 字段的名字
	FIELD_NAME varchar(100) COMMENT '字段的名字',
	-- 字段的类型
	FIELD_TYPE varchar(20) NOT NULL COMMENT '字段的类型',
	FIELD_LABEL varchar(100),
	PRIMARY KEY (REGISTER_ID, FIELD_ID, FORM_ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;


CREATE TABLE TBL_FORM_META
(
	-- form 编号
	FORM_ID bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'form 编号',
	-- form 名称
	FORM_NAME varchar(100) NOT NULL COMMENT 'form 名称',
	-- form 描述
	FORM_DESCRIPTION varchar(200) COMMENT 'form 描述',
	-- draft: 表示草稿
	-- publish: 表示发布
	-- inactive: 表示废弃
	STATUS varchar(10) DEFAULT '1' NOT NULL COMMENT 'draft: 表示草稿
publish: 表示发布
inactive: 表示废弃',
	-- raw json
	RAW_JSON varchar(3000) COMMENT 'raw json',
	FIELD_LABEL varchar(100),
	-- 创建时间戳
	CREATED_TIMESTAMP datetime DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '创建时间戳',
	-- 更新时间戳
	UPDATED_TIMESTAMP datetime DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '更新时间戳',
	PRIMARY KEY (FORM_ID),
	UNIQUE (FORM_NAME)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;


CREATE TABLE TBL_USER_INFO
(
	USER_ID varchar(40) NOT NULL,
	USER_NAME varchar(50) NOT NULL,
	FULL_NAME varchar(100),
	PASSWORD varchar(100) NOT NULL,
	MOBILE_PHONE varchar(20),
	DEPARTMENT varchar(100),
	TITLE varchar(100),
	USER_PHOTO_URL varchar(200),
	ACTIVE varchar(2) NOT NULL,
	CREATE_USER_ID varchar(40) NOT NULL,
	CREATE_USER_NAME varchar(50) NOT NULL,
	MODIFY_USER_ID varchar(40) NOT NULL,
	MODIFY_USER_NAME varchar(50) NOT NULL,
	CREATE_TIMESTAMP datetime NOT NULL,
	MODIFY_TIMESTAMP datetime NOT NULL,
	PRIMARY KEY (USER_ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;



/* Create Foreign Keys */

ALTER TABLE TBL_FORM_FIELD_OPTION
	ADD CONSTRAINT FK_FORM_FIELD_META FOREIGN KEY (FIELD_ID)
	REFERENCES TBL_FORM_FIELD_META (FIELD_ID)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;


ALTER TABLE TBL_FORM_FIELD_META
	ADD CONSTRAINT FK_FORM_META FOREIGN KEY (FORM_ID)
	REFERENCES TBL_FORM_META (FORM_ID)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;



/* Create Indexes */

CREATE UNIQUE INDEX FORM_FIELD_NAME USING BTREE ON TBL_FORM_FIELD_META (FIELD_NAME ASC, FORM_ID ASC);
CREATE INDEX FK_FORM_ID_INDEX USING BTREE ON TBL_FORM_FIELD_META (FORM_ID ASC);
CREATE INDEX INDEX_FORM_FIELD_VALUE ON TBL_FORM_FIELD_VALUE (FORM_ID DESC, FIELD_ID DESC, FIELD_VALUE DESC);
CREATE UNIQUE INDEX FORM_NAME_UNIQUE USING BTREE ON TBL_FORM_META (FORM_NAME ASC);



